//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Project {
            get {
                return ((int)(this["Project"]));
            }
            set {
                this["Project"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>CRM</string>\r\n  <string>INFOLINIA</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CRM {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CRM"]));
            }
            set {
                this["CRM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>NDTH</string>\r\n  <string>SR</string>\r\n  <string>CP</string>\r\n</ArrayOfStri" +
            "ng>")]
        public global::System.Collections.Specialized.StringCollection Billing {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Billing"]));
            }
            set {
                this["Billing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string loginWFS {
            get {
                return ((string)(this["loginWFS"]));
            }
            set {
                this["loginWFS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hasloWFS {
            get {
                return ((string)(this["hasloWFS"]));
            }
            set {
                this["hasloWFS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string loginJira {
            get {
                return ((string)(this["loginJira"]));
            }
            set {
                this["loginJira"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hasloJira {
            get {
                return ((string)(this["hasloJira"]));
            }
            set {
                this["hasloJira"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool czyDzwiek {
            get {
                return ((bool)(this["czyDzwiek"]));
            }
            set {
                this["czyDzwiek"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sounds/BikeHorn.wav")]
        public string dzwiekSciezka {
            get {
                return ((string)(this["dzwiekSciezka"]));
            }
            set {
                this["dzwiekSciezka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DoRealizacji2liniaBill")]
        public string assignedFilterName {
            get {
                return ((string)(this["assignedFilterName"]));
            }
            set {
                this["assignedFilterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DoPobrania2liniaBill")]
        public string unassignedFilterName {
            get {
                return ((string)(this["unassignedFilterName"]));
            }
            set {
                this["unassignedFilterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string>SOS</string>
  <string>PLK</string>
  <string>SBL</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Zamowienia {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Zamowienia"]));
            }
            set {
                this["Zamowienia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool czyObaDrzewa {
            get {
                return ((bool)(this["czyObaDrzewa"]));
            }
            set {
                this["czyObaDrzewa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool czyPowiadomienie {
            get {
                return ((bool)(this["czyPowiadomienie"]));
            }
            set {
                this["czyPowiadomienie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int IssuesCheckTimeout {
            get {
                return ((int)(this["IssuesCheckTimeout"]));
            }
            set {
                this["IssuesCheckTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Zgłoszenie zostało przyjęte")]
        public string KomentarzDoJira {
            get {
                return ((string)(this["KomentarzDoJira"]));
            }
            set {
                this["KomentarzDoJira"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hasloBillennium {
            get {
                return ((string)(this["hasloBillennium"]));
            }
            set {
                this["hasloBillennium"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<Users>
  <User>
    <login>prekawek</login>
    <loginJira>prekawek</loginJira>
    <sendMail>1</sendMail>
  </User>
  <User>
    <login>plachowicz</login>
    <loginJira>plachowicz</loginJira>
    <sendMail>1</sendMail>
  </User>
</Users>")]
        public global::System.Xml.XmlDocument Users {
            get {
                return ((global::System.Xml.XmlDocument)(this["Users"]));
            }
            set {
                this["Users"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Filtr I")]
        public string filter1name {
            get {
                return ((string)(this["filter1name"]));
            }
            set {
                this["filter1name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Filtr II")]
        public string filter2name {
            get {
                return ((string)(this["filter2name"]));
            }
            set {
                this["filter2name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string autoInterval {
            get {
                return ((string)(this["autoInterval"]));
            }
            set {
                this["autoInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string logSearchFolder {
            get {
                return ((string)(this["logSearchFolder"]));
            }
            set {
                this["logSearchFolder"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Parser 3.0.32.15")]
        public string AppVersion {
            get {
                return ((string)(this["AppVersion"]));
            }
        }
    }
}
